FORMAT: 1A
HOST: http://localhost:5000/api/v1

# Administração do Sistema Estação

API REST para efetuar a administração do Sistema Estação Metereológica localmente. 

# Group module

## module [/module]

### Listar todos os módulos instalados na Rasp [GET]

+ Response 200 (application/json)